# Main docker-compose.yml using 'include'
# Define global configurations like networks here.

# Networks from your monitoring file and previous setup
networks:
  homelab-net: # Renamed from {{ docker_network_name }} to be consistent.
    driver: bridge
    name: ${DOCKER_NETWORK_NAME:-homelab-net} # Use variable from .env, default to homelab-net
  monitoring_net: # From your monitoring file
    driver: bridge

# Top-level named volumes for Grafana and Prometheus data, now mapped to RAID
# This is an alternative to direct bind mounts if you prefer Docker-managed volumes
# whose data still lives on the RAID.
# For true "everything on RAID via bind mount" as per original goal, we will
# define paths directly in service volumes using HOST_DOCKER_DATA_PATH.
# The example below will use direct bind mounts for data.

include:
  - path: ./services/core.yml
  - path: ./services/development.yml
  - path: ./services/media.yml
  - path: ./services/monitoring.yml
  - path: ./services/custom-webapps.yml
  # - path: ./services/another_group.yml # Example: comment out to disable
