# ./services/media.yml
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${HOST_DOCKER_DATA_PATH}/sonarr/config:/config
      - ${HOST_DOCKER_DATA_PATH}/jellyfin/media/tvshows:/tv
      - ${HOST_DOCKER_DATA_PATH}/downloads/completed:/downloads
    ports:
      - "8989:8989"
    restart: unless-stopped
    networks:
      - homelab-net

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${HOST_DOCKER_DATA_PATH}/radarr/config:/config
      - ${HOST_DOCKER_DATA_PATH}/jellyfin/media/movies:/movies
      - ${HOST_DOCKER_DATA_PATH}/downloads/completed:/downloads
    ports:
      - "7878:7878"
    restart: unless-stopped
    networks:
      - homelab-net

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${HOST_DOCKER_DATA_PATH}/prowlarr/config:/config
    ports:
      - "9696:9696"
    restart: unless-stopped
    networks:
      - homelab-net

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - JELLYFIN_PublishedServerUrl=${JELLYFIN_SERVER_URL:-}
    volumes:
      - ${HOST_DOCKER_DATA_PATH}/jellyfin/config:/config
      - ${HOST_DOCKER_DATA_PATH}/jellyfin/media/tvshows:/data/tvshows
      - ${HOST_DOCKER_DATA_PATH}/jellyfin/media/movies:/data/movies
    ports:
      - "8096:8096"
      - "8920:8920"
    group_add:
      - "video" # Ensure this group exists on your Pi or find the correct GID
      # - "render"
    # devices: # Add if you have hardware transcoding working
      # - /dev/dri:/dev/dri
      # - /dev/vchiq:/dev/vchiq
    restart: unless-stopped
    networks:
      - homelab-net

  deluge:
    image: lscr.io/linuxserver/deluge:latest
    container_name: deluge
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - DELUGE_LOGLEVEL=error
    volumes:
      - ${HOST_DOCKER_DATA_PATH}/deluge/config:/config
      - ${HOST_DOCKER_DATA_PATH}/downloads:/downloads
    ports:
      - "8112:8112"
      - "6881:6881"
      - "6881:6881/udp"
    restart: unless-stopped
    networks:
      - homelab-net
